lang: en-US
title: Rob Rose Blog
description: "I press buttons on my computer and get paid to do it. (Sometimes)"
url: "https://blog.robrose.io/"

author:
  name: Rob Rose
  twitter: RobRoseKnows
  picture: /assets/img/slothme.png
twitter_username: RobRoseKnows
github_username: RobRoseKnows
logo: /assets/img/slothme.gif
search: false

markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

twitter:
  username: RobRoseKnows
  card: summary

social:
  name: Rob Rose
  links:
    - https://twitter.com/RobRoseKnows
    - https://linkedin.com/in/robertpaulrose
    - https://github.com/RobRoseKnows

paginate: 10
paginate_path: /page:num/
