remote_theme: rohanchandra/type-theme
title: Rob Rose Blog
description: "I press buttons on my computer and get paid to do it. (Sometimes)"
show_downloads: false
google_analytics: UA-66371735-3
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag