remote_theme: rohanchandra/type-theme
url: "https://blog.robrose.io/"
theme_settings:
  title: Rob Rose Blog
  avatar: assets/img/slothme.png
  description: "I press buttons on my computer and get paid to do it. (Sometimes)"
  show_downloads: false

  # Icons
  rss: true
  github: "RobRoseKnows"
  linkedin: "https://linkedin.com/in/robertpaulrose"
  twitter: "RobRoseKnows"

  # Scripts
  google_analytics: UA-66371735-3
  katex: true
  search: true
twitter:
  username: RobRoseKnows
  card: summary
social:
  name: Rob Rose
  links:
    - https://twitter.com/RobRoseKnows
    - https://linkedin.com/in/robertpaulrose
    - https://github.com/RobRoseKnows
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
